USE P3
GO

CREATE TABLE Product (
    productID INT IDENTITY(1,1) PRIMARY KEY,
    productName VARCHAR(255) UNIQUE NOT NULL, 
    manufacturer VARCHAR(255) NOT NULL, 
    skinType VARCHAR(11) NOT NULL CHECK (skinType IN('normal','oily','dry','combination','sensitive')),
    price SMALLMONEY NOT NULL CHECK (price>=0)
);

INSERT INTO Product
    (productName, manufacturer, skinType, price)
VALUES
    ('Differin 10% Benzoyl Peroxide Acne Spot Treatment', 'Differin', 'normal', 9.99),  
    ('CeraVe Hydrating Facial Cleanser', 'CeraVe', 'dry', 13.99),  
    ('Neutrogena Oil-Free Acne Wash', 'Neutrogena', 'oily', 8.49),  
    ('La Roche-Posay Toleriane Hydrating Cleanser', 'La Roche-Posay', 'sensitive', 14.99),
    ('Cetaphil Gentle Skin Cleanser', 'Cetaphil', 'combination', 10.49),  
    ('First Aid Beauty Pure Skin Face Cleanser', 'First Aid Beauty', 'sensitive', 12.00),
    ('Paula’s Choice Clear Pore Normalizing Cleanser', 'Paula’s Choice', 'normal', 14.00),  
    ('The Ordinary Squalane Cleanser', 'The Ordinary', 'dry', 7.90),  
    ('Kiehl’s Ultra Facial Cleanser', 'Kiehl’s', 'normal', 22.00),  
    ('Bioderma Sensibio H2O Micellar Water', 'Bioderma', 'sensitive', 11.99),  
    ('Vanicream Gentle Facial Cleanser', 'Vanicream', 'sensitive', 8.50),  
    ('Youth To The People Superfood Cleanser', 'Youth To The People', 'combination', 36.00),  
    ('Drunk Elephant Beste No.9 Jelly Cleanser', 'Drunk Elephant', 'oily', 32.00),  
    ('Garnier SkinActive Micellar Water', 'Garnier', 'normal', 8.99),  
    ('Tatcha The Deep Cleanse', 'Tatcha', 'combination', 38.00),  
    ('Origins Checks and Balances Frothy Face Wash', 'Origins', 'combination', 25.00),  
    ('Fresh Soy Face Cleanser', 'Fresh', 'normal', 38.00),  
    ('Clinique Liquid Facial Soap', 'Clinique', 'oily', 21.00),  
    ('Aveeno Calm + Restore Nourishing Oat Cleanser', 'Aveeno', 'sensitive', 9.99),  
    ('Eucerin Hydrating Cleansing Gel', 'Eucerin', 'dry', 10.50),
    ('The Inkey List Salicylic Acid Cleanser', 'The Inkey List', 'oily', 10.99),
    ('Olay Regenerist Regenerating Cream Cleanser', 'Olay', 'dry', 8.99),
    ('Murad Clarifying Cleanser', 'Murad', 'oily', 32.00),
    ('Simple Kind to Skin Refreshing Facial Wash', 'Simple', 'sensitive', 6.99),
    ('Farmacy Green Clean Makeup Removing Balm', 'Farmacy', 'combination', 36.00),
    ('Clinique Take The Day Off Cleansing Balm', 'Clinique', 'normal', 34.00),
    ('Thayers pH Balancing Daily Cleanser', 'Thayers', 'sensitive', 14.99),
    ('PanOxyl Acne Foaming Wash', 'PanOxyl', 'oily', 9.99),
    ('Mario Badescu Enzyme Cleansing Gel', 'Mario Badescu', 'normal', 14.00),
    ('Vichy Pureté Thermale 3-in-1 Cleanser', 'Vichy', 'combination', 18.50),
    ('Peach & Lily Power Calm Hydrating Gel Cleanser', 'Peach & Lily', 'sensitive', 28.00),
    ('Glow Recipe Blueberry Bounce Gentle Cleanser', 'Glow Recipe', 'normal', 34.00),
    ('Korres Greek Yoghurt Foaming Cream Cleanser', 'Korres', 'combination', 26.00),
    ('Herbivore Pink Cloud Creamy Jelly Cleanser', 'Herbivore', 'dry', 24.00),
    ('COSRX Low pH Good Morning Gel Cleanser', 'COSRX', 'oily', 12.00),
    ('DHC Deep Cleansing Oil', 'DHC', 'combination', 29.00),
    ('Tula Cult Classic Purifying Cleanser', 'Tula', 'normal', 28.00),
    ('Dr. Jart+ Cicapair Tiger Grass Enzyme Foam Cleanser', 'Dr. Jart+', 'sensitive', 28.00),
    ('Hada Labo Tokyo Gentle Hydrating Cleanser', 'Hada Labo', 'dry', 12.00),
    ('The Face Shop Rice Water Bright Light Cleansing Oil', 'The Face Shop', 'normal', 15.00),
    ('Bioré Charcoal Acne Daily Cleanser', 'Bioré', 'oily', 8.99),
    ('Neogen Real Fresh Foam Cleanser', 'Neogen', 'combination', 19.00),
    ('Shiseido Clarifying Cleansing Foam', 'Shiseido', 'normal', 36.00),
    ('Mamonde Petal Spa Oil to Foam Cleanser', 'Mamonde', 'sensitive', 21.00),
    ('Boscia Purifying Cleansing Gel', 'Boscia', 'oily', 26.00),
    ('Pixi Glow Tonic Cleansing Gel', 'Pixi', 'combination', 18.00),
    ('Elemis Superfood Facial Wash', 'Elemis', 'normal', 25.00),
    ('Laneige Cream Skin Milk Oil Cleanser', 'Laneige', 'dry', 34.00),
    ('Erborian Solid Cleansing Oil', 'Erborian', 'combination', 39.00),
    ('Kose Softymo Speedy Cleansing Oil', 'Kose', 'oily', 13.00),
    ('CeraVe Moisturizing Cream', 'CeraVe', 'dry', 18.99),  
    ('Neutrogena Hydro Boost Water Gel', 'Neutrogena', 'normal', 19.99),  
    ('La Roche-Posay Toleriane Double Repair Face Moisturizer', 'La Roche-Posay', 'sensitive', 19.49),  
    ('Cetaphil Daily Oil-Free Hydrating Lotion', 'Cetaphil', 'oily', 14.99),  
    ('First Aid Beauty Ultra Repair Cream', 'First Aid Beauty', 'sensitive', 36.00),  
    ('Aveeno Calm + Restore Oat Gel Moisturizer', 'Aveeno', 'normal', 23.00),  
    ('Drunk Elephant Protini Polypeptide Cream', 'Drunk Elephant', 'combination', 68.00),  
    ('The Ordinary Natural Moisturizing Factors + HA', 'The Ordinary', 'dry', 8.99),  
    ('Tatcha The Water Cream', 'Tatcha', 'oily', 70.00),  
    ('Olay Regenerist Micro-Sculpting Cream', 'Olay', 'combination', 24.99),  
    ('Kiehl’s Ultra Facial Cream', 'Kiehl’s', 'normal', 35.00),  
    ('Vanicream Moisturizing Lotion', 'Vanicream', 'sensitive', 12.99),  
    ('Eucerin Advanced Repair Lotion', 'Eucerin', 'dry', 11.99),  
    ('Paula’s Choice Omega+ Complex Moisturizer', 'Paula’s Choice', 'normal', 37.00),  
    ('Burt’s Bees Daily Face Moisturizer', 'Burt’s Bees', 'combination', 17.99),  
    ('Youth To The People Superfood Air-Whip Moisturizer', 'Youth To The People', 'oily', 48.00),  
    ('Biossance Squalane + Omega Repair Cream', 'Biossance', 'dry', 58.00),  
    ('Clinique Dramatically Different Moisturizing Lotion+', 'Clinique', 'normal', 32.50),  
    ('EltaMD AM Therapy Facial Moisturizer', 'EltaMD', 'combination', 36.00),  
    ('Aquaphor Healing Ointment', 'Aquaphor', 'sensitive', 13.99),  
    ('Belif The True Cream Aqua Bomb', 'Belif', 'oily', 38.00),  
    ('Glow Recipe Banana Soufflé Moisture Cream', 'Glow Recipe', 'normal', 39.00),  
    ('Murad Hydro-Dynamic Ultimate Moisture', 'Murad', 'dry', 75.00),  
    ('Weleda Skin Food Original Ultra-Rich Cream', 'Weleda', 'dry', 18.99),  
    ('Shiseido Benefiance Wrinkle Smoothing Cream', 'Shiseido', 'combination', 70.00),  
    ('Kora Organics Turmeric Glow Moisturizer', 'Kora Organics', 'sensitive', 58.00),  
    ('Mario Badescu Aloe Moisturizer', 'Mario Badescu', 'normal', 24.00),  
    ('Pixi H2O Skin Drink', 'Pixi', 'oily', 22.00),  
    ('Avene Tolerance Control Soothing Skin Recovery Cream', 'Avene', 'sensitive', 35.00),  
    ('Sunday Riley Ice Ceramide Moisturizing Cream', 'Sunday Riley', 'dry', 65.00),  
    ('The Inkey List Vitamin B, C, and E Moisturizer', 'The Inkey List', 'normal', 8.99),  
    ('Origins GinZing Oil-Free Energy-Boosting Gel Moisturizer', 'Origins', 'oily', 32.00),  
    ('COSRX Oil-Free Ultra-Moisturizing Lotion', 'COSRX', 'combination', 25.00),  
    ('Tula 24-7 Moisture Hydrating Day & Night Cream', 'Tula', 'normal', 48.00),  
    ('Clinique Moisture Surge 72-Hour Auto-Replenishing Hydrator', 'Clinique', 'oily', 42.00),  
    ('Farmacy Honey Halo Ultra-Hydrating Ceramide Moisturizer', 'Farmacy', 'dry', 45.00),  
    ('Hada Labo Tokyo Skin Plumping Gel Cream', 'Hada Labo', 'combination', 24.00),  
    ('Embryolisse Lait-Crème Concentré', 'Embryolisse', 'normal', 16.00),  
    ('Sebamed Clear Face Care Gel', 'Sebamed', 'oily', 20.00),  
    ('Pond’s Dry Skin Cream', 'Pond’s', 'dry', 7.99),  
    ('Vichy Aqualia Thermal Rich Cream', 'Vichy', 'combination', 31.00),  
    ('Curel Ultra Healing Lotion', 'Curel', 'dry', 9.99),  
    ('Nivea Soft Moisturizing Cream', 'Nivea', 'normal', 5.99),  
    ('Dermalogica Active Moist', 'Dermalogica', 'oily', 42.00),  
    ('The Face Shop Chia Seed Hydro Lotion', 'The Face Shop', 'combination', 22.00),  
    ('Lubriderm Daily Moisture Lotion', 'Lubriderm', 'normal', 8.99),  
    ('Ceramedx Ultra Moisturizing Cream', 'Ceramedx', 'dry', 14.99),  
    ('SkinFix Barrier+ Triple Lipid-Peptide Cream', 'SkinFix', 'sensitive', 50.00),  
    ('Gold Bond Healing Lotion', 'Gold Bond', 'dry', 9.99),  
    ('Aveeno Daily Moisturizing Lotion', 'Aveeno', 'normal', 11.99);