USE P3
GO

CREATE TABLE Product (
    productID INT IDENTITY(1,1) PRIMARY KEY,
    productName VARCHAR(255) UNIQUE NOT NULL, 
    manufacturer VARCHAR(255) NOT NULL, 
    productType VARCHAR(30) NOT NULL CHECK (productType IN('Cleanser','Moisturizer','Sunscreen','Acne Treatment','Serum','Eye Cream','Mask','Toner','Exfoliant')),
    skinType VARCHAR(11) NOT NULL CHECK (skinType IN('normal','oily','dry','combination','sensitive')),
    price SMALLMONEY NOT NULL CHECK (price>=0)
);

INSERT INTO Product
    (productName, manufacturer, productType, skinType, price)
VALUES
    ('Differin 10% Benzoyl Peroxide Acne Spot Treatment', 'Differin', 'Acne Treatment','normal', 9.99),  
    ('CeraVe Hydrating Facial Cleanser', 'CeraVe', 'Cleanser','dry', 13.99),  
    ('Neutrogena Oil-Free Acne Wash', 'Neutrogena', 'Cleanser','oily', 8.49),  
    ('La Roche-Posay Toleriane Hydrating Cleanser', 'La Roche-Posay', 'Cleanser','sensitive', 14.99),
    ('Cetaphil Gentle Skin Cleanser', 'Cetaphil', 'Cleanser','combination', 10.49),  
    ('First Aid Beauty Pure Skin Face Cleanser', 'First Aid Beauty', 'Cleanser','sensitive', 12.00),
    ('Paula’s Choice Clear Pore Normalizing Cleanser', 'Paula’s Choice', 'Cleanser','normal', 14.00),  
    ('The Ordinary Squalane Cleanser', 'The Ordinary', 'Cleanser','dry', 7.90),  
    ('Kiehl’s Ultra Facial Cleanser', 'Kiehl’s', 'Cleanser','normal', 22.00),  
    ('Bioderma Sensibio H2O Micellar Water', 'Bioderma', 'Cleanser','sensitive', 11.99),  
    ('Vanicream Gentle Facial Cleanser', 'Vanicream', 'Cleanser','sensitive', 8.50),  
    ('Youth To The People Superfood Cleanser', 'Youth To The People', 'Cleanser','combination', 36.00),  
    ('Drunk Elephant Beste No.9 Jelly Cleanser', 'Drunk Elephant', 'Cleanser','oily', 32.00),  
    ('Garnier SkinActive Micellar Water', 'Garnier', 'Cleanser','normal', 8.99),  
    ('Tatcha The Deep Cleanse', 'Tatcha', 'Cleanser','combination', 38.00),  
    ('Origins Checks and Balances Frothy Face Wash', 'Origins', 'Cleanser','combination', 25.00),  
    ('Fresh Soy Face Cleanser', 'Fresh', 'Cleanser','normal', 38.00),  
    ('Clinique Liquid Facial Soap', 'Clinique', 'Cleanser','oily', 21.00),  
    ('Aveeno Calm + Restore Nourishing Oat Cleanser', 'Aveeno', 'Cleanser','sensitive', 9.99),  
    ('Eucerin Hydrating Cleansing Gel', 'Eucerin', 'Cleanser','dry', 10.50),
    ('The Inkey List Salicylic Acid Cleanser', 'The Inkey List', 'Cleanser','oily', 10.99),
    ('Olay Regenerist Regenerating Cream Cleanser', 'Olay', 'Cleanser','dry', 8.99),
    ('Murad Clarifying Cleanser', 'Murad', 'Cleanser','oily', 32.00),
    ('Simple Kind to Skin Refreshing Facial Wash', 'Simple', 'Cleanser','sensitive', 6.99),
    ('Farmacy Green Clean Makeup Removing Balm', 'Farmacy', 'Cleanser','combination', 36.00),
    ('Clinique Take The Day Off Cleansing Balm', 'Clinique', 'Cleanser','normal', 34.00),
    ('Thayers pH Balancing Daily Cleanser', 'Thayers', 'Cleanser','sensitive', 14.99),
    ('PanOxyl Acne Foaming Wash', 'PanOxyl', 'Cleanser','oily', 9.99),
    ('Mario Badescu Enzyme Cleansing Gel', 'Mario Badescu', 'Cleanser','normal', 14.00),
    ('Vichy Pureté Thermale 3-in-1 Cleanser', 'Vichy', 'Cleanser','combination', 18.50),
    ('Peach & Lily Power Calm Hydrating Gel Cleanser', 'Peach & Lily', 'Cleanser','sensitive', 28.00),
    ('Glow Recipe Blueberry Bounce Gentle Cleanser', 'Glow Recipe', 'Cleanser','normal', 34.00),
    ('Korres Greek Yoghurt Foaming Cream Cleanser', 'Korres', 'Cleanser','combination', 26.00),
    ('Herbivore Pink Cloud Creamy Jelly Cleanser', 'Herbivore', 'Cleanser','dry', 24.00),
    ('COSRX Low pH Good Morning Gel Cleanser', 'COSRX', 'Cleanser','oily', 12.00),
    ('DHC Deep Cleansing Oil', 'DHC', 'Cleanser','combination', 29.00),
    ('Tula Cult Classic Purifying Cleanser', 'Tula', 'Cleanser','normal', 28.00),
    ('Dr. Jart+ Cicapair Tiger Grass Enzyme Foam Cleanser', 'Dr. Jart+', 'Cleanser','sensitive', 28.00),
    ('Hada Labo Tokyo Gentle Hydrating Cleanser', 'Hada Labo', 'Cleanser','dry', 12.00),
    ('The Face Shop Rice Water Bright Light Cleansing Oil', 'The Face Shop', 'Cleanser','normal', 15.00),
    ('Bioré Charcoal Acne Daily Cleanser', 'Bioré', 'Cleanser','oily', 8.99),
    ('Neogen Real Fresh Foam Cleanser', 'Neogen', 'Cleanser','combination', 19.00),
    ('Shiseido Clarifying Cleansing Foam', 'Shiseido', 'Cleanser','normal', 36.00),
    ('Mamonde Petal Spa Oil to Foam Cleanser', 'Mamonde', 'Cleanser','sensitive', 21.00),
    ('Boscia Purifying Cleansing Gel', 'Boscia', 'Cleanser','oily', 26.00),
    ('Pixi Glow Tonic Cleansing Gel', 'Pixi', 'Cleanser','combination', 18.00),
    ('Elemis Superfood Facial Wash', 'Elemis', 'Cleanser','normal', 25.00),
    ('Laneige Cream Skin Milk Oil Cleanser', 'Laneige', 'Cleanser','dry', 34.00),
    ('Erborian Solid Cleansing Oil', 'Erborian', 'Cleanser','combination', 39.00),
    ('Kose Softymo Speedy Cleansing Oil', 'Kose', 'Cleanser','oily', 13.00),
    ('CeraVe Moisturizing Cream', 'CeraVe', 'Moisturizer','dry', 18.99),  
    ('Neutrogena Hydro Boost Water Gel', 'Neutrogena', 'Moisturizer','normal', 19.99),  
    ('La Roche-Posay Toleriane Double Repair Face Moisturizer', 'La Roche-Posay', 'Moisturizer','sensitive', 19.49),  
    ('Cetaphil Daily Oil-Free Hydrating Lotion', 'Cetaphil', 'Moisturizer','oily', 14.99),  
    ('First Aid Beauty Ultra Repair Cream', 'First Aid Beauty', 'Moisturizer','sensitive', 36.00),  
    ('Aveeno Calm + Restore Oat Gel Moisturizer', 'Aveeno', 'Moisturizer','normal', 23.00),  
    ('Drunk Elephant Protini Polypeptide Cream', 'Drunk Elephant', 'Moisturizer','combination', 68.00),  
    ('The Ordinary Natural Moisturizing Factors + HA', 'The Ordinary', 'Moisturizer','dry', 8.99),  
    ('Tatcha The Water Cream', 'Tatcha', 'Moisturizer','oily', 70.00),  
    ('Olay Regenerist Micro-Sculpting Cream', 'Olay', 'Moisturizer','combination', 24.99),  
    ('Kiehl’s Ultra Facial Cream', 'Kiehl’s', 'Moisturizer','normal', 35.00),  
    ('Vanicream Moisturizing Lotion', 'Vanicream', 'Moisturizer','sensitive', 12.99),  
    ('Eucerin Advanced Repair Lotion', 'Eucerin', 'Moisturizer','dry', 11.99),  
    ('Paula’s Choice Omega+ Complex Moisturizer', 'Paula’s Choice', 'Moisturizer','normal', 37.00),  
    ('Burt’s Bees Daily Face Moisturizer', 'Burt’s Bees', 'Moisturizer','combination', 17.99),  
    ('Youth To The People Superfood Air-Whip Moisturizer', 'Youth To The People', 'Moisturizer','oily', 48.00),  
    ('Biossance Squalane + Omega Repair Cream', 'Biossance', 'Moisturizer','dry', 58.00),  
    ('Clinique Dramatically Different Moisturizing Lotion+', 'Clinique', 'Moisturizer','normal', 32.50),  
    ('EltaMD AM Therapy Facial Moisturizer', 'EltaMD', 'Moisturizer','combination', 36.00),  
    ('Aquaphor Healing Ointment', 'Aquaphor', 'Moisturizer','sensitive', 13.99),  
    ('Belif The True Cream Aqua Bomb', 'Belif', 'Moisturizer','oily', 38.00),  
    ('Glow Recipe Banana Soufflé Moisture Cream', 'Glow Recipe', 'Moisturizer','normal', 39.00),  
    ('Murad Hydro-Dynamic Ultimate Moisture', 'Murad', 'Moisturizer','dry', 75.00),  
    ('Weleda Skin Food Original Ultra-Rich Cream', 'Weleda', 'Moisturizer','dry', 18.99),  
    ('Shiseido Benefiance Wrinkle Smoothing Cream', 'Shiseido', 'Moisturizer','combination', 70.00),  
    ('Kora Organics Turmeric Glow Moisturizer', 'Kora Organics', 'Moisturizer','sensitive', 58.00),  
    ('Mario Badescu Aloe Moisturizer', 'Mario Badescu', 'Moisturizer','normal', 24.00),  
    ('Pixi H2O Skin Drink', 'Pixi', 'Moisturizer','oily', 22.00),  
    ('Avene Tolerance Control Soothing Skin Recovery Cream', 'Avene', 'Moisturizer','sensitive', 35.00),  
    ('Sunday Riley Ice Ceramide Moisturizing Cream', 'Sunday Riley', 'Moisturizer','dry', 65.00),  
    ('The Inkey List Vitamin B, C, and E Moisturizer', 'The Inkey List', 'Moisturizer','normal', 8.99),  
    ('Origins GinZing Oil-Free Energy-Boosting Gel Moisturizer', 'Origins', 'Moisturizer','oily', 32.00),  
    ('COSRX Oil-Free Ultra-Moisturizing Lotion', 'COSRX', 'Moisturizer','combination', 25.00),  
    ('Tula 24-7 Moisture Hydrating Day & Night Cream', 'Tula', 'Moisturizer','normal', 48.00),  
    ('Clinique Moisture Surge 72-Hour Auto-Replenishing Hydrator', 'Clinique', 'Moisturizer','oily', 42.00),  
    ('Farmacy Honey Halo Ultra-Hydrating Ceramide Moisturizer', 'Farmacy', 'Moisturizer','dry', 45.00),  
    ('Hada Labo Tokyo Skin Plumping Gel Cream', 'Hada Labo', 'Moisturizer','combination', 24.00),  
    ('Embryolisse Lait-Crème Concentré', 'Embryolisse', 'Moisturizer','normal', 16.00),  
    ('Sebamed Clear Face Care Gel', 'Sebamed', 'Moisturizer','oily', 20.00),  
    ('Pond’s Dry Skin Cream', 'Pond’s', 'Moisturizer','dry', 7.99),  
    ('Vichy Aqualia Thermal Rich Cream', 'Vichy', 'Moisturizer','combination', 31.00),  
    ('Curel Ultra Healing Lotion', 'Curel', 'Moisturizer','dry', 9.99),  
    ('Nivea Soft Moisturizing Cream', 'Nivea', 'Moisturizer','normal', 5.99),  
    ('Dermalogica Active Moist', 'Dermalogica', 'Moisturizer','oily', 42.00),  
    ('The Face Shop Chia Seed Hydro Lotion', 'The Face Shop', 'Moisturizer','combination', 22.00),  
    ('Lubriderm Daily Moisture Lotion', 'Lubriderm', 'Moisturizer','normal', 8.99),  
    ('Ceramedx Ultra Moisturizing Cream', 'Ceramedx', 'Moisturizer','dry', 14.99),  
    ('SkinFix Barrier+ Triple Lipid-Peptide Cream', 'SkinFix', 'Moisturizer','sensitive', 50.00),  
    ('Gold Bond Healing Lotion', 'Gold Bond', 'Moisturizer','dry', 9.99),  
    ('Aveeno Daily Moisturizing Lotion', 'Aveeno', 'Moisturizer','normal', 11.99),
    ('Neutrogena Ultra Sheer Dry-Touch Sunscreen', 'Neutrogena', 'Sunscreen','normal', 8.99),  
    ('La Roche-Posay Anthelios Melt-in Milk', 'La Roche-Posay', 'Sunscreen','sensitive', 29.99),  
    ('EltaMD UV Clear Broad-Spectrum SPF 46', 'EltaMD', 'Sunscreen','combination', 39.00),  
    ('Supergoop! Unseen Sunscreen SPF 40', 'Supergoop!', 'Sunscreen','oily', 36.00),  
    ('CeraVe Hydrating Mineral Sunscreen', 'CeraVe', 'Sunscreen','dry', 13.99),  
    ('Blue Lizard Australian Sunscreen', 'Blue Lizard', 'Sunscreen','sensitive', 16.99),  
    ('Banana Boat Ultra Sport Sunscreen Lotion', 'Banana Boat', 'Sunscreen','normal', 7.99),  
    ('Aveeno Positively Mineral Sunscreen', 'Aveeno', 'Sunscreen','dry', 11.99),  
    ('Coola Organic Scalp & Hair Mist', 'Coola', 'Sunscreen','combination', 26.00),  
    ('Coppertone Pure & Simple Baby Sunscreen', 'Coppertone', 'Sunscreen','sensitive', 12.99),  
    ('Sun Bum Original SPF 30 Sunscreen', 'Sun Bum', 'Sunscreen','normal', 15.99),  
    ('Hawaiian Tropic Silk Hydration Sunscreen', 'Hawaiian Tropic', 'Sunscreen','oily', 10.99),  
    ('ISDIN Eryfotona Actinica', 'ISDIN', 'Sunscreen','combination', 55.00),  
    ('Babo Botanicals Clear Zinc Sunscreen', 'Babo Botanicals', 'Sunscreen','sensitive', 14.99),  
    ('Thinkbaby Safe Sunscreen', 'Thinkbaby', 'Sunscreen','normal', 9.99),  
    ('Vanicream SPF 50 Sunscreen', 'Vanicream', 'Sunscreen','dry', 12.49),  
    ('Shiseido Ultimate Sun Protector Lotion', 'Shiseido', 'Sunscreen','combination', 49.00),  
    ('Olay Regenerist Mineral Sunscreen', 'Olay', 'Sunscreen','normal', 28.99),  
    ('Alba Botanica Hawaiian Sunscreen', 'Alba Botanica', 'Sunscreen','oily', 9.49),  
    ('Bare Republic Mineral Sunscreen', 'Bare Republic', 'Sunscreen','sensitive', 14.99),  
    ('Bioderma Photoderm Nude Touch', 'Bioderma', 'Sunscreen','combination', 19.99),  
    ('Peter Thomas Roth Max Mineral Naked Sunscreen', 'Peter Thomas Roth', 'Sunscreen','normal', 38.00),  
    ('Murad City Skin Age Defense SPF 50', 'Murad', 'Sunscreen','sensitive', 65.00),  
    ('Tatcha Silken Pore Perfecting Sunscreen', 'Tatcha', 'Sunscreen','oily', 65.00),  
    ('Kiehl’s Activated Sun Protector Lotion', 'Kiehl’s', 'Sunscreen','normal', 32.00),  
    ('Pacifica Mineral Sunscreen Spray', 'Pacifica', 'Sunscreen','dry', 13.99),  
    ('La Roche-Posay Anthelios Mineral Tinted SPF 50', 'La Roche-Posay', 'Sunscreen','combination', 33.99),  
    ('Dermalogica Invisible Physical Defense SPF 30', 'Dermalogica', 'Sunscreen','sensitive', 54.00),  
    ('Biossance Squalane + Zinc Sheer Sunscreen', 'Biossance', 'Sunscreen','normal', 30.00),  
    ('Altruist Dermatologist Sunscreen SPF 50', 'Altruist', 'Sunscreen','oily', 10.49),  
    ('Bondi Sands Fragrance-Free Face Sunscreen', 'Bondi Sands', 'Sunscreen','combination', 12.99),  
    ('Glow Recipe Watermelon Glow Sunscreen', 'Glow Recipe', 'Sunscreen','oily', 34.00),  
    ('Drunk Elephant Umbra Sheer Physical Daily Defense', 'Drunk Elephant', 'Sunscreen','dry', 36.00),  
    ('Cetaphil Sheer Mineral Sunscreen', 'Cetaphil', 'Sunscreen','sensitive', 10.99),  
    ('Neutrogena Hydro Boost Water Gel Lotion', 'Neutrogena', 'Sunscreen','combination', 13.99),  
    ('CeraVe 100% Mineral Sunscreen Stick', 'CeraVe', 'Sunscreen','normal', 9.99),  
    ('ThinkSport SPF 50 Sunscreen', 'ThinkSport', 'Sunscreen','dry', 14.99),  
    ('EltaMD UV Daily Tinted SPF 40', 'EltaMD', 'Sunscreen','combination', 33.50),  
    ('Coppertone Sport Clear Lotion', 'Coppertone', 'Sunscreen','normal', 10.99),  
    ('Australian Gold Botanical Tinted Face Sunscreen', 'Australian Gold', 'Sunscreen','oily', 15.99),  
    ('Paula’s Choice Extra Care Non-Greasy Sunscreen', 'Paula’s Choice', 'Sunscreen','combination', 25.00),  
    ('Sun Bum Mineral SPF 50 Sunscreen', 'Sun Bum', 'Sunscreen','sensitive', 17.99),  
    ('Kiss My Face Face Factor Sunscreen', 'Kiss My Face', 'Sunscreen','normal', 13.49),  
    ('Babo Botanicals Baby Skin Mineral Sunscreen', 'Babo Botanicals', 'Sunscreen','sensitive', 19.99),  
    ('Aveeno Protect + Hydrate Sunscreen', 'Aveeno', 'Sunscreen','normal', 11.99),  
    ('Blue Lizard Face Mineral Sunscreen', 'Blue Lizard', 'Sunscreen','sensitive', 14.99),  
    ('Hawaiian Tropic Antioxidant+ Sunscreen', 'Hawaiian Tropic', 'Sunscreen','oily', 12.99),  
    ('Banana Boat Light As Air Face Lotion', 'Banana Boat', 'Sunscreen','combination', 7.99),  
    ('Supergoop! Glow Screen SPF 40', 'Supergoop!', 'Sunscreen','oily', 38.00),
    ('Altruist Dermatologist Face Fluid SPF 50+', 'Altruist', 'Sunscreen','normal', 11.99),
    ('The Ordinary Niacinamide 10% + Zinc 1%', 'The Ordinary', 'Serum', 'oily', 5.90),  
    ('Skinceuticals C E Ferulic', 'Skinceuticals', 'Serum', 'normal', 166.00),  
    ('La Roche-Posay Hyalu B5 Serum', 'La Roche-Posay', 'Serum', 'dry', 39.99),  
    ('Drunk Elephant T.L.C. Framboos Glycolic Night Serum', 'Drunk Elephant', 'Serum', 'combination', 90.00),
    ('Paula’s Choice Skin Perfecting 2% BHA Liquid Exfoliant', 'Paula’s Choice', 'Exfoliant', 'oily', 32.00),  
    ('Tatcha The Rice Polish Foaming Enzyme Powder', 'Tatcha', 'Exfoliant', 'sensitive', 65.00),  
    ('Neutrogena Alcohol-Free Toner', 'Neutrogena', 'Toner', 'normal', 7.49),  
    ('Pixi Glow Tonic', 'Pixi', 'Toner', 'combination', 29.00),  
    ('Thayers Witch Hazel Toner', 'Thayers', 'Toner', 'sensitive', 10.95),  
    ('Kiehl’s Ultra Facial Toner', 'Kiehl’s', 'Toner', 'dry', 18.00),  
    ('Laneige Water Sleeping Mask', 'Laneige', 'Mask', 'combination', 25.00),  
    ('Fresh Rose Face Mask', 'Fresh', 'Mask', 'sensitive', 25.00),  
    ('Glow Recipe Watermelon Glow Sleeping Mask', 'Glow Recipe', 'Mask', 'normal', 45.00),  
    ('Peter Thomas Roth Cucumber Gel Mask', 'Peter Thomas Roth', 'Mask', 'sensitive', 52.00),  
    ('La Mer The Eye Concentrate', 'La Mer', 'Eye Cream', 'dry', 245.00),  
    ('Olay Eyes Brightening Eye Cream', 'Olay', 'Eye Cream', 'normal', 29.99),  
    ('Kiehl’s Creamy Eye Treatment with Avocado', 'Kiehl’s', 'Eye Cream', 'combination', 32.00),  
    ('Drunk Elephant C-Tango Multivitamin Eye Cream', 'Drunk Elephant', 'Eye Cream', 'normal', 64.00),  
    ('The Inkey List Caffeine Eye Cream', 'The Inkey List', 'Eye Cream', 'oily', 9.99),  
    ('Biossance Squalane + Peptide Eye Gel', 'Biossance', 'Eye Cream', 'sensitive', 54.00);